### ISSUE TITLE
Add `sleep` operation

### ISSUE THREAD

**Issue by eddycharly** [kyverno/chainsaw#494]
Add `sleep` operation to avoid using script or command and have to mess with the timeout.

Do not forget:
- tests
- docs
- validation

**Comment by swastik959** [comment]
@eddycharly hi I want to work on this issue can you please explain it to me in a bit more detail

**Comment by shubham-cmyk** [comment]
If you look at the operation over here: https://github.com/kyverno/chainsaw/tree/main/pkg/runner/operations
You have to add another operation called sleep so that users don't need to use commands or script operation to use the `sleep utility` 

Make sure that there is a timeout per operation so that the timeout here should be greater that the `sleep time` This needs to be done in the validation.

**Comment by eddycharly** [comment]
@swastik959 

1. add the new `Sleep` struct in the api.
2. create the corresponding operation in `pkg/runner/operations`
3. modify processors in `pkg/runner/processors`
4. add validation logic in `pkg/validation`

**Comment by eddycharly** [comment]
@swastik959 are you planning to work on this ?

**Comment by swastik959** [comment]
@eddycharly yes

**Comment by shubham-cmyk** [comment]
@swastik959 You can open the draft if you are facing any issues

**Comment by eddycharly** [comment]
@swastik959 did you start working on this or shall i pick it up ?

**Comment by eddycharly** [comment]
@swastik959 can you share your progress ? when do you plan to submit a PR ?

**Comment by eddycharly** [comment]
@swastik959 i took some time to implement it https://github.com/kyverno/chainsaw/pull/566 i hope you didn't spend too much time on it
